#!/usr/bin/python3

"""
A class decralation for new teble
Table name: cities
"""

from model_state import Base
from sqlalchemy import Column, Integer, String, ForeignKey


class Cities(Base):
    """Cities table inhirits Base class imported
    from model_state module

    Args:
        id: Integer, autogenerated & not null
        name: cities name, string & not null
        state_id: Integer, forign key to state.id
    """
    __tablename__ = 'cities'
    id = Column(Integer, primary_key=True, autoincrement=True, nullabe=False)
    name = Column(String(128), nullable=False)
    state_id = Column(Integer, ForeignKey('states.id'), nullable=False)
